# Generated by Django 4.1.3 on 2022-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzatime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='specialty',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
